### ISSUE TITLE
APEX

### ISSUE THREAD

**Issue by D0907A** [oleksandrblazhko/ai-211-amitsi#25]
необхідність підключення до віддаленого серверу СКБД Oracle

**Comment by oleksandrblazhko** [comment]
Доброго дня.
На Oracle-севері для вас створено обліковий запис:
login = amitsi
password = p1P34ab#

Приклад встановлення з'єднання через SQLPlus:
sqlplus amitsi/p1P34ab#@185.235.218.67:1521/XEPDB1

Приклад програмного коду java-програми із
методами доступу до Oracle БД наведено
в лабораторній роботі.
